from agents.data_agent import data_agent
from langchain_core.messages import HumanMessage

if __name__ == "__main__":
    response = data_agent.invoke(
        {"messages":[HumanMessage(content="Show me the top 2 payment methods used by customers in the last 6 months and also show me the total revenue generated by each payment method")],
         "route_response": ""}
    )

    last_message = response["messages"][-1]
    route = response["route_response"]

    print(f"\n{'='*50}")
    print(f"Route: {route.upper()}")
    print(f"{'='*50}\n")

    if route == "sql":
        # sql_analyst ka poora result dict hai
        print(last_message["final_answer"])
    elif route == "etl":
        # etl_analyst ka result LangChain message object hai
        print(last_message["messages"][-1].content)

    print(f"\n{'='*50}\n")